### ISSUE TITLE
Takip etmediğim takipçilerim ve beni takip etmeyen takiplerimin listesi

### ISSUE THREAD

**Issue by mustafadalga** [ilteriskeskin/github-followers-tracker#1]
Selamlar @ilteriskeskin :) ,
Emeğine sağlık.

Takip etmediğim takipçilerim ve beni takip etmeyen takiplerimin listesi olarak iki farklı liste şeklinde listeyebilirsin diye öneride bulunmak istedim.🙂

**Comment by ilteriskeskin** [comment]
Selamlar, önerin için teşekkür ederim :) Bunu aceleyle çıkardım eksiklere pr açılır diye düşünüyorum ama önerini dikkate alıp hafta sonu onla ilgili bir şeyler deneyeyim :)

**Comment by mustafadalga** [comment]
Uygulamayı Flask ile yapmıssın. 2 sene önce bakmıştım öylesine.Şuan pek bilmediğim için öneri olarak söylemek istedim :)

**Comment by ilteriskeskin** [comment]
Anladım teşekkür ederim ilk boş vaktimde ilgileneceğim :)
